### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by lee-you** [Tencent/libpag#1557]
2023-07-11 17:16:19.937 com.newvpn.test E/AndroidRuntime: FATAL EXCEPTION: pagImageView-renderer
    Process: com.newvpn.test, PID: 23722
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.libpag.PAGDecoder.copyFrameTo(android.graphics.Bitmap, int)' on a null object reference
        at org.libpag.PAGImageView.a(SourceFile:57)
        at org.libpag.PAGImageView.flush(SourceFile:13)
        at org.libpag.PAGImageView.r(SourceFile:4)
        at org.libpag.b$b.handleMessage(SourceFile:40)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)

## 【版本信息】

4.2.88

## 【平台信息】

Android 原生

## 【预期的表现】
PAGImageView 切换pag文件播放时不会崩溃

## 【实际的情况】
PAGImageView 切换pag文件播放时偶现崩溃

**Comment by kevingpqi123** [comment]
该问题已修复，可以升级到 4.2.99
