### ISSUE TITLE
Android PAGImageView崩溃：width and height must be > 0

### ISSUE THREAD

**Issue by zengke328** [Tencent/libpag#1623]
## 【版本信息】

4.2.100

## 【平台信息】

Android 原生 

## 【预期的表现】

PAGImageView宽高异常处理

## 【实际的情况】

Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1123)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1090)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1040)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1001)
       at org.libpag.PAGImageView.a(SourceFile:57)
       at org.libpag.PAGImageView.flush(SourceFile:30)
       at org.libpag.PAGImageView.s(SourceFile:4)
       at org.libpag.b$b.handleMessage(SourceFile:40)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by h3r3x3** [comment]
已经修复，下个小版本发版时候带入修复
