### ISSUE TITLE
偶现无法加载pag图标

### ISSUE THREAD

**Issue by hnubility** [Tencent/libpag#1650]
## 【版本信息】

[4.0.5.10](com.tencent.tav:libpag:4.0.5.10-noffavc)

## 【平台信息】

Android 原生

## 【预期的表现】
加载后无法显示PAG动画

## 【实际的情况】
at org.libpag.GPUDecoder.dequeueInputBuffer(GPUDecoder.java:120)
2023-01-03 11:49:08.161 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.onSendBytes(GPUDecoder.java:170)
2023-01-03 11:49:08.161 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.dequeueOutputBuffer(GPUDecoder.java:111)
2023-01-03 11:49:08.161 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.onDecodeFrame(GPUDecoder.java:196)
2023-01-03 11:49:08.161 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.dequeueInputBuffer(GPUDecoder.java:120)
2023-01-03 11:49:08.161 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.onSendBytes(GPUDecoder.java:170)
2023-01-03 11:49:08.161 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.dequeueOutputBuffer(GPUDecoder.java:111)
2023-01-03 11:49:08.162 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.onDecodeFrame(GPUDecoder.java:196)
2023-01-03 11:49:08.162 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.dequeueInputBuffer(GPUDecoder.java:120)
2023-01-03 11:49:08.162 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.onSendBytes(GPUDecoder.java:170)
2023-01-03 11:49:08.162 31011-31266 System.err              com.oplus.aod                        W  	at org.libpag.GPUDecoder.dequeueOutputBuffer(GPUDecoder.java:111)
2023-01-03 11:49:08.162 31011-31266 S
全是这个异常

![image](https://github.com/Tencent/libpag/assets/7478601/ea6e6c6e-09e1-466a-8c7f-474c95489b81)

start异常

**Comment by kevingpqi123** [comment]
1、首先确认使用的 pag 文件是否含有 BMP 预合成，如果是纯矢量的素材和这里没有关系，就要查看自己使用的情况；
2、如果使用的是含有 BMP 预合成的素材，看下使用的 pag 版本是否含有 noffavc，noffavc的版本默认是没有内置软解的，如果硬解失败，会出现无法显示的问题，如果使用的是不带后缀的版本，内部带有软解，硬解失败会回退软解

**Comment by domchen** [comment]
Android的硬解是会存在概率性失败的，所以默认的包比较大的那个是带了软件解码的回退保障你能显示出来。看看是不是用了noffavc的版本，这个版本主要是给你外部注入的情况下使用的，比如App里已经带了个ffempg不想重复嵌入，希望可以复用就可以实现一下pag的软解接口注入。如果没有注入就需要使用标准的版本。
