### ISSUE TITLE
java.util.concurrent.TimeoutException: org.libpag.PAGAnimator.finalize() timed out after 60 seconds

### ISSUE THREAD

**Issue by xs93** [Tencent/libpag#1672]
## 【版本信息】

4.3.3

## 【平台信息】

Android 原生

## 【实际的情况】
监听PAGImageView的动画中，PAGImageView.isPlaying()方法偶然崩溃

************Crash Log Head************
Device Manufacturer : samsung
Brand               : samsung 
Device Model        : SM-N9810
Android Version     : 13_33
CPU ABI             : arm64-v8a,armeabi-v7a,armeabi,
************Crash Log Head************
java.util.concurrent.TimeoutException: org.libpag.PAGAnimator.finalize() timed out after 60 seconds
	at org.libpag.PAGAnimator.isRunning(Native Method)
	at org.libpag.PAGImageView.isPlaying(SourceFile:1)
	at org.libpag.PAGImageView.onAnimationCancel(SourceFile:5)
	at org.libpag.PAGAnimator.onAnimationCancel(SourceFile:3)
	at org.libpag.PAGAnimator.nativeFinalize(Native Method)
	at org.libpag.PAGAnimator.finalize(SourceFile:1)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
	at java.lang.Daemons$Daemon.run(Daemons.java:140)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by kevingpqi123** [comment]
建议提供复现的 demo 工程及复现步骤

**Comment by CodeJhF** [comment]
因为用户近期没有反馈，所以暂时关闭当前issue，如果后续有问题再重新打开
