### ISSUE TITLE
crash for libpag:4.2.61

### ISSUE THREAD

**Issue by liuyuesheng** [Tencent/libpag#1679]
java.lang.NullPointerException: Attempt to get length of null array
at java.util.ArrayList.toArray(ArrayList.java:405)
at android.animation.Animator.callOnList(Animator.java:665)
at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1645)
at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:771)
at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:734)
at org.libpag.PAGView.f(SourceFile:9)
at org.libpag.PAGView.play(SourceFile:5)

**Comment by kevingpqi123** [comment]
该问题很早就修复了，请升级至 4.2 的最新版本或 4.3
