### ISSUE TITLE
Android 14上出现崩溃，pag版本 4.2.100

### ISSUE THREAD

**Issue by zcgl** [Tencent/libpag#1796]
## 【版本信息】
4.2.100

## 【平台信息】
Android 原生   全部是 Android 14

## 【预期的表现】
正常展示

## 【实际的情况】
出现崩溃
Thread 23860 Crashed:
NullPointerException: Attempt to get length of null array
at java.util.ArrayList.toArray(ArrayList.java:405)
at android.animation.Animator.callOnList(Animator.java:665)
at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1645)
at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:771)
at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:734)
at org.libpag.PAGView.flush(SourceFile:10)

## 【Demo及附件】
量级逐渐上升了

**Comment by zcgl** [comment]
at org.libpag.PAGView.flush(SourceFile:10)
    at org.libpag.PAGView.o(SourceFile:4)
    at org.libpag.PAGView.b(SourceFile:1)
    at org.libpag.PAGView$g.handleMessage(SourceFile:49)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.os.HandlerThread.run(HandlerThread.java:67)
    at com.zhihu.android.threadRuler.thread.RulerHandlerThread.run(RulerHandlerThread.kt:41)

**Comment by tohodog** [comment]
同有这个问题

**Comment by simplezhli** [comment]
我这边线上刚发现一个，也是Android14。
![image](https://github.com/Tencent/libpag/assets/12456431/4d164e80-7586-4518-a781-cacfafdfffdb)

**Comment by simplezhli** [comment]
https://github.com/Tencent/libpag/issues/1679#issuecomment-1685744480 的回答有些问题。看了一下代码，发现是5月29号修改这块代码，但是4.2.100版本并未合并进去。目前看只能升到4.3.33观察一下了。

**Comment by CodeJhF** [comment]
因为用户近期没有反馈，所以暂时关闭当前issue，如果后续有问题再重新打开
