### ISSUE TITLE
PAGImageView 初始化报错

### ISSUE THREAD

**Issue by yu123yue** [Tencent/libpag#1797]
## 【版本信息】

4.2.100 和4.2.104

## 【平台信息】

Android 原生

## 【Demo及附件】
2023-10-26 16:26:49.311 18686-18686 rth.angel.voic          com.skyworth.angel.voice             A  java_vm_ext.cc:542]   native: #124 pc 007feb79  [stack] (???)
2023-10-26 16:26:49.311 18686-18686 rth.angel.voic          com.skyworth.angel.voice             A  java_vm_ext.cc:542]   at java.lang.Runtime.nativeLoad(Native method)
2023-10-26 16:26:49.311 18686-18686 rth.angel.voic          com.skyworth.angel.voice             A  java_vm_ext.cc:542]   at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
2023-10-26 16:26:49.311 18686-18686 rth.angel.voic          com.skyworth.angel.voice             A  java_vm_ext.cc:542]   - locked <0x0be827de> (a java.lang.Runtime)
2023-10-26 16:26:49.311 18686-18686 rth.angel.voic          com.skyworth.angel.voice             A  java_vm_ext.cc:542]   at java.lang.System.loadLibrary(System.java:1669)
2023-10-26 16:26:49.311 18686-18686 rth.angel.voic          com.skyworth.angel.voice             A  java_vm_ext.cc:542]   at org.extra.tools.a.a(SourceFile:7)
2023-10-26 16:26:49.311 18686-18686 rth.angel.voic          com.skyworth.angel.voice             A  java_vm_ext.cc:542]   at org.extra.tools.a.b(SourceFile:8)
2023-10-26 16:26:49.311 18686-18686 rth.angel.voic          com.skyworth.angel.voice             A  java_vm_ext.cc:542]   at org.extra.tools.a.b(SourceFile:7)
2023-10-26 16:26:49.311 18686-18686 rth.angel.voic          com.skyworth.angel.voice             A  java_vm_ext.cc:542]   at org.libpag.PAGImageView.<clinit>(SourceFile:835)

**Comment by kevingpqi123** [comment]
建议完善信息，仅仅上面的堆栈难以定位问题，目前 4.2.100 和 4.2.104 已经在大范围使用了
针对你这边提出的问题，建议完善下面的信息：
1）是否必现？ 2） 如果偶现，是否有复现路径  3）偶现是该问题出现的概率 4）完成的 crash信息，堆栈、log 信息等

**Comment by CodeJhF** [comment]
因为用户近期没有反馈，所以暂时关闭当前issue，如果后续有问题再重新打开
