### ISSUE TITLE
Android 4.3.33 java.lang.NullPointerException

### ISSUE THREAD

**Issue by cc519348051** [Tencent/libpag#1960]
## 【版本信息】

4.3.33

## 【平台信息】

Android 原生  Android14机型会报这个错误

## 【Demo及附件】
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void android.animation.ValueAnimator$AnimatorUpdateListener.onAnimationUpdate(android.animation.ValueAnimator)' on a null object reference
       at android.animation.Animator$AnimatorCaller.lambda$static$4(Animator.java:858)
       at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda6.call(:4)
       at android.animation.Animator.callOnList(Animator.java:669)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1645)
       at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:771)
       at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:734)
       at org.libpag.PAGView.flush(SourceFile:8)
       at org.libpag.PAGView.n(SourceFile:2)
       at org.libpag.PAGView.a(SourceFile:1)
       at org.libpag.PAGView$a.handleMessage(SourceFile:16)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by domchen** [comment]
你这个不是 4.3.33 版本的堆栈，在 4.3.33 版本里 PAGView 已经没有用 ValueAnimator了。历史的版本是可能存在类似问题，可以升级一下最新的版本，并确保升级成功了。如果这个真的是你线上的堆栈，说明用的不是 4.3.33版本。
