### ISSUE TITLE
当使用PAG库4.2.17版本时，在华为Android8.0手机上执行PAGFile.Load代码闪退

### ISSUE THREAD

**Issue by wscjy** [Tencent/libpag#2145]
## 【版本信息】

4.2.17

## 【平台信息】

Android 原生
设备：华为荣耀9 STF-AL10
android版本：8.0

## 【预期的表现】
正常加载pag动画文件

## 【实际的情况】
app在设备上运行时加载pag文件闪退，使用之前版本[4.1.49](https://github.com/Tencent/libpag/releases/tag/v4.1.49)则无此问题

## bugly记录
 E  #++++++++++Record By Bugly++++++++++#
 E  # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
 E  # APP VER: 3.0.1
 E  # SDK VER: 4.1.9.3-4.1.9.3
 E  # LAUNCH TIME: 2024-02-20 17:45:44
 E  # CRASH TYPE: NATIVE_CRASH
 E  # CRASH TIME: 2024-02-20 17:46:12
 D  isAppForeground:false
 E  # CRASH FOREGROUND: false
 E  # CRASH THREAD: main(17308)
 E  # REPORT ID: c507d0b1-b405-4da8-a7eb-0a97020d09b4
 E  # CRASH DEVICE: STF-AL10 UNROOT
 E  # RUNTIME AVAIL RAM:3193696256 ROM:1734344704 SD:1713373184
 E  # RUNTIME TOTAL RAM:6007898112 ROM:56302223360 SD:56281251840
 E  # CRASH STACK: 
 E  SIGABRT
    0x292c0000439c
    #00    pc 0000000000069fec    /system/lib64/libc.so (tgkill+8) [arm64-v8a::76a0cdf3f6a85fe656d057d2f7dfce4c]
    #01    pc 000000000001dad0    /system/lib64/libc.so (abort+88) [arm64-v8a::76a0cdf3f6a85fe656d057d2f7dfce4c]
    #02    pc 00000000004380cc    /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+528) [arm64-v8a::1402f1b69fc9caf829e0a69fb345950a]
    #03    pc 00000000004387dc    /system/lib64/libart.so (_ZN3art7Runtime7AborterEPKc+24) [arm64-v8a::1402f1b69fc9caf829e0a69fb345950a]
    #04    pc 0000000000523e58    /system/lib64/libart.so (_ZN7android4base10LogMessageD1Ev+900) [arm64-v8a::1402f1b69fc9caf829e0a69fb345950a]
    #05    pc 00000000002d5c78    /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1716) [arm64-v8a::1402f1b69fc9caf829e0a69fb345950a]
    #06    pc 00000000002d5f44    /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+176) [arm64-v8a::1402f1b69fc9caf829e0a69fb345950a]
    #07    pc 0000000000317a14    /system/lib64/libart.so (_ZN3art3JNI10NewObjectVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+908) [arm64-v8a::1402f1b69fc9caf829e0a69fb345950a]
    #08    pc 00000000000cde60    /data/app/com.**.metahomes.test-3Ub5e9paJ6WZrRcINwceFg==/lib/arm64/libpag.so [arm64-v8a::474326ba66fd0363159a2a951473e527]
    #09    pc 00000000000cecc4    /data/app/com.**.metahomes.test-3Ub5e9paJ6WZrRcINwceFg==/lib/arm64/libpag.so [arm64-v8a::474326ba66fd0363159a2a951473e527]
    #10    pc 00000000000d17bc    /data/app/com.**.metahomes.test-3Ub5e9paJ6WZrRcINwceFg==/lib/arm64/libpag.so (Java_org_libpag_PAGFile_LoadFromAssets+264) [arm64-v8a::47432
    #11    pc 0000000000197218    /data/app/com.**.metahomes.test-3Ub5e9paJ6WZrRcINwceFg==/oat/arm64/base.odex (oatexec+299544) [arm64-v8a::f56924ecd0f0168bb6243a2ed417a6ff]
    java:
    org.libpag.PAGFile.Load(SourceFile:3)
    com.metarent.global.ext.pag.UtilsPagKt.getPagView(UtilsPag.kt:71)
    com.metarent.global.ext.pag.UtilsPagKt.getPagView$default(UtilsPag.kt:23)
    com.metarent.global.MainActivity$animView$2.invoke(MainActivity.kt:268)
    com.metarent.global.MainActivity$animView$2.invoke(MainActivity.kt:268)
    kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    com.metarent.global.MainActivity.getAnimView(MainActivity.kt:268)
    com.metarent.global.MainActivity.initHouseKeeper(MainActivity.kt:275)
    com.metarent.global.MainActivity.initData(MainActivity.kt:72)
    com.metarent.commons.ui.mvvm.BaseMvvmActivity.onCreate(BaseMvvmActivity.kt:21)
    android.app.Activity.performCreate(Activity.java:7372)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
    android.app.ActivityThread.-wrap12(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
    android.os.Handler.dispatchMessage(Handler.java:108)
    android.os.Looper.loop(Looper.java:166)
    android.app.ActivityThread.main(ActivityThread.java:7425)

                                                                                                    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
 E  #++++++++++++++++++++++++++++++++++++++++++#

**Comment by wfd2022** [comment]
最新版本在Linux编译后运行PAGFile的Load函数也会出现段错误，刚刚试了楼主的版本是正常的

**Comment by wscjy** [comment]
您好，我已收到您的邮件，我会尽快给您回复。

**Comment by wscjy** [comment]
> 最新版本在Linux编译后运行PAGFile的Load函数也会出现段错误，刚刚试了楼主的版本是正常的

是否于华为EMUI8.0.0版本设备上测试无复现？

**Comment by kevingpqi123** [comment]
一个版本系列，尽量使用最新的版本，比如 4.2 版本，使用 4.2.100，请基于最新的版本做测试

**Comment by wscjy** [comment]
> 一个版本系列，尽量使用最新的版本，比如 4.2 版本，使用 4.2.100，请基于最新的版本做测试

基于4.2.100 sdk版本测试，报错如下：
 E  FATAL EXCEPTION: main
                                                                                                    Process: com.**.metahomes.test, PID: 21979
                                                                                                    java.lang.VerifyError: Verifier rejected class org.extra.tools.c: void org.extra.tools.c.onResume() failed to verify: void org.extra.tools.c.onResume(): [0x28] thrown class Reference: java.lang.Object not instanceof Throwable (declaration of 'org.extra.tools.c' appears in /data/app/com.**.metahomes.test-XY91j2fRUmQXrPFDM3HvSw==/base.apk:classes25.dex)
                                                                                                    	at org.extra.tools.b.a(SourceFile:12)
                                                                                                    	at org.libpag.PAGView.k(SourceFile:1)
                                                                                                    	at org.libpag.PAGView.<init>(SourceFile:854)
                                                                                                    	at com.metarent.global.ext.pag.UtilsPagKt.getPagView(UtilsPag.kt:66)
                                                                                                    	at com.metarent.global.ext.pag.UtilsPagKt.getPagView$default(UtilsPag.kt:23)
                                                                                                    	at com.metarent.global.MainActivity$animView$2.invoke(MainActivity.kt:268)
                                                                                                    	at com.metarent.global.MainActivity$animView$2.invoke(MainActivity.kt:268)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.metarent.global.MainActivity.getAnimView(MainActivity.kt:268)
                                                                                                    	at com.metarent.global.MainActivity.initHouseKeeper(MainActivity.kt:275)
                                                                                                    	at com.metarent.global.MainActivity.initData(MainActivity.kt:72)
                                                                                                    	at com.metarent.commons.ui.mvvm.BaseMvvmActivity.onCreate(BaseMvvmActivity.kt:21)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7372)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
                                                                                                    	at android.app.ActivityThread.-wrap12(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:108)
                                                                                                    	at android.os.Looper.loop(Looper.java:166)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7425)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
