### ISSUE TITLE
4.3.57版本概率出现释放卡死导致进程无响应

### ISSUE THREAD

**Issue by AtomHong** [Tencent/libpag#2322]
## 【版本信息】

4.3.57

## 【平台信息】

Android 原生

## 【预期的表现】

onCancel阶段设置progress为0

## 【实际的情况】

05-23 20:40:43.080  2204  2259 E AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
05-23 20:40:43.080  2204  2259 E AndroidRuntime: Process: ****, PID: 2204
05-23 20:40:43.080  2204  2259 E AndroidRuntime: java.util.concurrent.TimeoutException: org.libpag.PAGAnimator.finalize() timed out after 10 seconds
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at org.libpag.PAGAnimator.setProgress(Native Method)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at org.libpag.PAGView.setProgress(SourceFile:2)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at com.****.settings_ui.fragment.****$adapter$2$1$1$playAnimation$1.onAnimationCancel(****.kt:163)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at org.libpag.PAGView.onAnimationCancel(SourceFile:5)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at org.libpag.PAGAnimator.onAnimationCancel(SourceFile:3)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at org.libpag.PAGAnimator.nativeFinalize(Native Method)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at org.libpag.PAGAnimator.finalize(SourceFile:1)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at java.lang.Daemons$Daemon.run(Daemons.java:137)
05-23 20:40:43.080  2204  2259 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
05-23 20:40:22.878   802  1460 I InputDispatcher: Application is not responding: Window{df30193 u0

**Comment by kevingpqi123** [comment]
关于 ANR 问题：
1、首先要明确一个问题，不是所有的 pag 文件的性能都是一样的，如果遇到性能的问题，首先是排查素材，如果素材很复杂，首先去优化素材而不是其它的，如果素材很简单出现了卡顿，那才需要去排查是否是使用问题

业界没有可以兼容所有复杂素材的动效渲染方案，**根本的解决办法就是分机型下发素材，不要期望复杂素材（含有 BMP 预合成的素材）可以在所有机型上没有卡顿问题**

对于 pag sdk，可以这么理解，本来这些动效是自己需要代码实现的，性能本质上和动效的复杂度强相关，现在 pag sdk 将这些动效实现封装成了 SDK

2、使用层面，pag 内部已经做了多线程相关的处理，只有一个场景需要注意，避免播放的过程中去直接销毁，销毁的操作在主线程，但异步渲染需要主环境的 surface ，因此这里存在等待，需要注意的就是这一个点，这是使用中最普遍的问题


3、如果你们实现功能的时候很蹩脚或者耗费了很多精力，这种实现方案大概率都不是最优的，这种场景我们没有办法覆盖，只能说你们遇到了这类问题确定方案的时候最好事先咨询下
根据目前的对接情况：
问题1 占比 60%、问题2 占比 30%，问题3 占比 10%

如果不涉及全屏播放、文本编辑、占位图替换和实色图层修改颜色，PAGView 可以切换至 PAGImageView，PAGImageView 支持缓存渲染结果，可以大幅降低概率（但不能从根本解决，首次渲染的时候仍有可能出现）。

**Comment by peter100u** [comment]
看到您说的第二种情况， “只有一个场景需要注意，避免播放的过程中去直接销毁”，我看到我们业务有一种情况，我们的礼物数据是一个队列，播放完成后再获取一个新的资源，每次播放完都会设置重新设置pAGView.visibility = View.GONE，然后重新加载资源，特殊的点在于： pagviewListener的onAnimationCancel回调的时候，也重新获取下个资源同时设置 pAGView.visibility = View.GONE，再次加载， 这里的 onAnimationCancel是否就是异常情况，pAGView.visibility = View.GONE就是销毁的意思呢

**Comment by kevingpqi123** [comment]
> 我们的产品线上也是大量的org.libpag.PAGAnimator.finalize() timed out after 10 seconds，但是线上pag资源多大上千个资源，而且海外机型也特别复杂，能否提供一个方案，解析pag资源遇到性能问题，能提供警告日志回调，业务方可以针对资源优化呢

pag 官网上面的文档建议系统阅读下，可以避免很多问题，我们提供了桌面预览工具，可以定性去查看一些素材的性能：
https://pag.art/docs/profiler.html
如果桌面端预览性能栏有红色，在中低端机上大概率会出现卡顿
https://pag.art/docs/optimization.html
还有严格控制 BMP 预合成的数量，这些都是和性能强相关

**Comment by kevingpqi123** [comment]
> 看到您说的第二种情况， “只有一个场景需要注意，避免播放的过程中去直接销毁”，我看到我们业务有一种情况，我们的礼物数据是一个队列，播放完成后再获取一个新的资源，每次播放完都会设置重新设置pAGView.visibility = View.GONE，然后重新加载资源，特殊的点在于： pagviewListener的onAnimationCancel回调的时候，也重新获取下个资源同时设置 pAGView.visibility = View.GONE，再次加载， 这里的 onAnimationCancel是否就是异常情况，pAGView.visibility = View.GONE就是销毁的意思呢

如果是多个 pag 文件顺序播放，可以了解下 pag 的组合模式，自己创建一个 PAGComposition，然后将多个 pag 文件添加进来，通过 setStartTime 可以设置相对于主时间轴的开始时间，pag 支持多个原子素材的自由组合，具体用法可以参考下 pag 的官方 demo，性能肯定比你现在的方案要好很多

**Comment by AtomHong** [comment]
非常感谢回复

**Comment by peter100u** [comment]
> > 看到您说的第二种情况， “一个场景需要注意，避免播放但去销毁”，我们见到的业务都是这样。 情况是，我们的礼物数据是一个队列，播放完成后再获取一个新的资源，每次播放完都会设置重新设置pAGView.visibility = View.GONE，然后重新加载资源，特殊点在于： pagviewListener的onAnimationCancel函数的时候，也重新获取下一个资源同时设置 pAGView.visibility = View.GONE，再次加载， 这个onAnimationCancel是否就是异常情况，pAGView.visibility = View.GONE就是销毁
> 
> 如果是多个 pag 文件顺序播放，可以了解下 pag 的组合模式，自己创建一个 PAGComposition，然后将多个 pag 文件添加进来，通过 setStartTime 可以设置相对于主时间轴的开始时间，使用一个 PAGView 就可以实现你这边需要的，而且不需要你提到的那些设置，pag 支持多个原子素材的自由组合，具体用法可以参考下 pag 的官方演示，性能肯定比你现在的方案要好很多

感谢回复，现在的业务逻辑太复杂了，礼物队列的维护逻辑太多了，变化太多了，您这个方案，改动起来风险太大了

**Comment by peter100u** [comment]
@kevingpqi123 您好， 希望给提供其他方案或者定位问题，
1. 大量的org.libpag.PAGAnimator.finalize() timed out after 10 seconds，但是线上pag资源多大上千个资源， 无法手动排除资源问题；
2. 不能使用多个 PAGComposition，然后将多个 pag 文件添加进来，因为礼物具备优先级各种逻辑，不是顺序播放，
3. pAGView.visibility = View.GONE是否就是销毁pagview呢
希望能提供一些建议，线上org.libpag.PAGAnimator.finalize() timed out after 10 seconds实在太多了

**Comment by YauLam** [comment]
"避免播放的过程中去直接销毁"，这个销毁指的是freeCache，还是removPAGView，亦或是其他什么呢

**Comment by peter100u** [comment]
有没有其他方案可以解决这个问题呢

**Comment by RainbowDDB** [comment]
这里实际上是一个死锁问题，路径为 nativeFinalize -> JPEGAnimator#clear -> onAnimationCancel -> PAGView#setComposition -> PAGAnimator#setProgress -> JPEGAnimator#get

用的是 mutex 非递归锁，最终应用在 FinalizeDaemon 线程死锁了

<img width="539" alt="image" src="https://github.com/user-attachments/assets/31199109-7ed5-4fa4-8ad5-89822cb7f80e" />

这里官方并没有明确说明 onAnimationCancel 中不能做什么，官方的 demo 中也只是打印了一行日志...

**Comment by Zllllll** [comment]
我这也出现了这个。应该怎么去解决呢？第一次使用pag库。对他不是特别了解。

**Comment by lianyagang** [comment]
大部分情况都是org.libpag.PAGPlayer 监听了finalize,这里当系统触发GC 的时候，会回调。进而调用了nativeFinalize，再查看cpp源码
PAG_API void Java_org_libpag_PAGPlayer_nativeFinalize(JNIEnv* env, jobject thiz) {
  setPAGPlayer(env, thiz, nullptr);
}
setPAGPlayer(env, thiz, nullptr) {
  // 1. 获取当前指针
  auto old = reinterpret_cast<JPAGPlayer*>(env->GetLongField(thiz, PAGPlayer_nativeContext));
  
  // 2. 删除资源对象
  if (old != nullptr) {
    delete old; // 内存释放!!
  }
  
  // 3. 设置新指针（null）
  env->SetLongField(thiz, PAGPlayer_nativeContext, (jlong)nullptr);
}
当执行到相关Player 方法时，例如，我的是setScale,会调用到源码
auto getPAGPlayer(JNIEnv* env, jobject thiz) {
  // A. 获取nativeContext值（此时可能正值或刚置0）
  auto jPlayer = reinterpret_cast<JPAGPlayer*>(
      env->GetLongField(thiz, PAGPlayer_nativeContext)
  );
  
  // B. 访问已释放内存
  if (jPlayer == nullptr) return nullptr; // 检查通过，但...
  return jPlayer->get(); // ⚠️ C++对象已删除!野指针访问
}
主线程执行到 getPAGPlayer 时：
env->GetLongField 可能返回 ​被删除但尚未置0的指针值​
if (jPlayer == nullptr) 检查通过​（非空）
jPlayer->get() 尝试访问已释放内存 → ​SIGSEGV​
继而导致了崩溃。这边的源码设计，不是很理解，为什么要去监听GC 回调呢？如果是内存紧张。应该让调用方来优化。而不是擅自把内存回收了。所以，大部分的崩溃，基本都是基于这个了。作者提到的优化PAG素材。其实很难做的。物料有的时候，是远程下发的。不可能做到性能一致的。

**Comment by 333bkz** [comment]
这个问题一直没解决。现在都不敢配pag资源了
