### ISSUE TITLE
setProgress调用造成ANR

### ISSUE THREAD

**Issue by coolstar1204** [Tencent/libpag#2614]
## 【版本信息】
4.2.100

## 【平台信息】
Android 原生

## 【预期的表现】
加载一个PAG文件后，特定逻辑下，只设置progress，展示首帧图片。不进行play播放

## 【实际的情况】
`anr time : 1733726988112011 ms
suspend all histogram:	Sum: 2.337ms 99% C.I. 1us-313.200us Avg: 41us Max: 328us
DALVIK THREADS (178):
"main" prio=5 tid=1 Native
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x736d0408 self=0xb4000072e7842c00
  | sysTid=7110 nice=0 cgrp=foreground sched=0/0 handle=0x739abe14f8
  | state=S schedstat=( 60454649696 9492469439 75826 ) utm=4163 stm=1882 core=2 HZ=100
  | stack=0x7fef0d0000-0x7fef0d2000 stackSize=8188KB
  | held mutexes=
  native: #00 pc 000902fc  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28) (BuildId: 84a42637b3a421b801818f5793418fca)
  native: #01 pc 000950d0  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex+144) (BuildId: 84a42637b3a421b801818f5793418fca)
  native: #02 pc 00103268  /apex/com.android.runtime/lib64/bionic/libc.so (NonPI::MutexLockWithTimeout+328) (BuildId: 84a42637b3a421b801818f5793418fca)
  native: #03 pc 00218654  /data/app/~~MAipB9hyLmq7z7dDtNMgNg==/cn.kuwo.player-wU95TOjkhgHh3Filr4fhJA==/lib/arm64/libpag.so (???) (BuildId: cd4ab68341f372634220a1af5a0fff348a052e72)
  native: #04 pc 0009ca1c  /data/app/~~MAipB9hyLmq7z7dDtNMgNg==/cn.kuwo.player-wU95TOjkhgHh3Filr4fhJA==/lib/arm64/libpag.so (pag::PAGPlayer::setProgress+76) (BuildId: cd4ab68341f372634220a1af5a0fff348a052e72)
  native: #05 pc 000ffc6c  /data/app/~~MAipB9hyLmq7z7dDtNMgNg==/cn.kuwo.player-wU95TOjkhgHh3Filr4fhJA==/lib/arm64/libpag.so (Java_org_libpag_PAGPlayer_setProgress+80) (BuildId: cd4ab68341f372634220a1af5a0fff348a052e72)
  at org.libpag.PAGPlayer.setProgress(Native method)
  at org.libpag.PAGView.setProgress(unavailable:5)
  - locked <0x057681aa> (a java.lang.Object)
  at cn.kuwo.ui.nowplay.widget.KwPAGView.setProgress(unavailable:0)
  at cn.kuwo.ui.online.adapter.ab.a$b.onAnimationEnd(unavailable:12)
  at org.libpag.PAGView.h(unavailable:28)
  at org.libpag.PAGView.f(unavailable:0)
  at org.libpag.PAGView$b.onAnimationEnd(unavailable:46)
  at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:711)
  at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda1.call(unavailable:4)
  at android.animation.Animator.callOnList(Animator.java:669)
  at android.animation.Animator.notifyListeners(Animator.java:608)
  at android.animation.Animator.notifyEndListeners(Animator.java:633)
  at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1306)`

**Comment by CodeJhF** [comment]
抱歉这条当时没有被跟进到，是我们漏了。

因长期无回复，且 libpag 4.3 及更早版本已停止维护（当前仅维护 4.4 / 4.5），先关闭本条。
上报版本：4.2.100 / 2.337。

如果问题在最新版本（4.4 / 4.5）仍能复现，欢迎在本帖回复或新开 issue，并附上 libpag 版本号、平台与系统版本、可复现的 PAG 文件或最小 demo，我们会优先跟进。（stale-close）
