### ISSUE TITLE
pagView线上使用后，遇到一个崩溃

### ISSUE THREAD

**Issue by xiaobaDev** [Tencent/libpag#617]
看了下代码，current在activity.isDestroyed()的时候还是可能位空的
           if (current == null && !activity.isDestroyed()) {
                current = (LifecycleFragment) fm.findFragmentByTag(FRAGMENT_TAG);
                if (current == null) {
                    current = new LifecycleFragment();
                    pendingRequestManagerFragments.put(fm, current);
                    fm.beginTransaction().add(current, FRAGMENT_TAG).commitAllowingStateLoss();
                    handler.obtainMessage(ID_REMOVE_FRAGMENT_MANAGER, fm).sendToTarget();
                }
            }
            current.addListener(pagView);
}

Process Name: 'com.zq.live'
Thread Name: 'main'
Back traces starts.
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.extra.tools.LifecycleFragment.a(org.extra.tools.LifecycleListener)' on a null object reference
	at org.extra.tools.Lifecycle.addListener(Lifecycle.java:47)
	at org.libpag.PAGView.setupSurfaceTexture(PAGView.java:317)
	at org.libpag.PAGView.<init>(PAGView.java:234)

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7830)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [p2{Cancelling}@27c5109, Dispatchers.Main]
Back traces ends.

## Which Version of libpag are you using?

libpag 4.0.5.79

## What Platform are you on? 

iOS 12, Android 10, macOS 10.15.3, Chrome 87.0  ...

**Comment by xiaobaDev** [comment]
4.0.5.82已经修复
