### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by juenuo** [Tencent/libpag#971]
## Which Version of libpag are you using?

libpag 4.2.77

## What Platform are you on? 

huawei HarmonyOS 10

**Comment by juenuo** [comment]
Process Name: 'com.tnt.madepingzi'
Thread Name: 'pag-renderer'
Back traces starts.
java.lang.ArithmeticException: divide by zero
	at org.libpag.PAGView.flush(SourceFile:7)
	at org.libpag.PAGView.n(SourceFile:2)
	at org.libpag.PAGView.b(SourceFile:1)
	at org.libpag.PAGView$g.handleMessage(SourceFile:16)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Back traces ends.

**Comment by kevingpqi123** [comment]
The issue has been fixed and you can upgrade to 4.2.88.
